#ifndef OPENCVCOMPAT_H
#define OPENCVCOMPAT_H

#include <opencv2/opencv.hpp>

#if CV_MAJOR_VERSION < 3
#define DI_CV_IMREAD_COLOR CV_LOAD_IMAGE_COLOR
#define DI_CV_IMREAD_GRAYSCALE CV_LOAD_IMAGE_GRAYSCALE
#define DI_CV_COLOR_GRAY2BGR CV_GRAY2BGR
#define DI_CV_COLOR_BGR2GRAY CV_BGR2GRAY
#define DI_CV_COLOR_BGR2RGB CV_BGR2RGB
#define DI_CV_COLOR_BGRA2RGBA CV_BGRA2RGBA
#define DI_CV_COLOR_RGB2BGR CV_RGB2BGR
#define DI_CV_THRESH_BINARY CV_THRESH_BINARY
#define DI_CV_THRESH_BINARY_INV CV_THRESH_BINARY_INV
#define DI_CV_THRESH_OTSU CV_THRESH_OTSU
#define DI_CV_MORPH_RECT CV_SHAPE_RECT
#define DI_CV_MORPH_OPEN CV_MOP_OPEN
#define DI_CV_MORPH_CLOSE CV_MOP_CLOSE
#define DI_CV_RETR_EXTERNAL CV_RETR_EXTERNAL
#define DI_CV_CHAIN_APPROX_SIMPLE CV_CHAIN_APPROX_SIMPLE
#define DI_CV_FONT_HERSHEY_SIMPLEX CV_FONT_HERSHEY_SIMPLEX
#define DI_CV_NORM_MINMAX CV_MINMAX
#else
#define DI_CV_IMREAD_COLOR cv::IMREAD_COLOR
#define DI_CV_IMREAD_GRAYSCALE cv::IMREAD_GRAYSCALE
#define DI_CV_COLOR_GRAY2BGR cv::COLOR_GRAY2BGR
#define DI_CV_COLOR_BGR2GRAY cv::COLOR_BGR2GRAY
#define DI_CV_COLOR_BGR2RGB cv::COLOR_BGR2RGB
#define DI_CV_COLOR_BGRA2RGBA cv::COLOR_BGRA2RGBA
#define DI_CV_COLOR_RGB2BGR cv::COLOR_RGB2BGR
#define DI_CV_THRESH_BINARY cv::THRESH_BINARY
#define DI_CV_THRESH_BINARY_INV cv::THRESH_BINARY_INV
#define DI_CV_THRESH_OTSU cv::THRESH_OTSU
#define DI_CV_MORPH_RECT cv::MORPH_RECT
#define DI_CV_MORPH_OPEN cv::MORPH_OPEN
#define DI_CV_MORPH_CLOSE cv::MORPH_CLOSE
#define DI_CV_RETR_EXTERNAL cv::RETR_EXTERNAL
#define DI_CV_CHAIN_APPROX_SIMPLE cv::CHAIN_APPROX_SIMPLE
#define DI_CV_FONT_HERSHEY_SIMPLEX cv::FONT_HERSHEY_SIMPLEX
#define DI_CV_NORM_MINMAX cv::NORM_MINMAX
#endif

#endif
